---
title: "Cell Chat Report"
format: html
embed-resources: true
---

# Normoxia P14 from USC data

```{r load_setup, message=FALSE}
library(CellChat)
cch <- readRDS('data/cch_ours_P14Norm.rds')
df.net <- subsetCommunication(cch)
groupSize <- as.numeric(table(cch@idents))

```

```{r, database}
CellChatDB <- CellChatDB.mouse
showDatabaseCategory(CellChatDB)
```


```{r, circles, fig.height=8.5}
#netVisual_circle(cch@net$count, vertex.weight = groupSize, weight.scale = T, label.edge= F, title.name = "Number of interactions")
#netVisual_circle(cch@net$weight, vertex.weight = groupSize, weight.scale = T, label.edge= F, title.name = "Interaction weights/strength")
for(ct in c('Myofibroblast','AT1','AT2 1','AT2 2')){
  # "Interaction weights/strength"
  netVisual_circle(cch@net$weight, vertex.weight = groupSize, weight.scale = T, label.edge= F, title.name = ct,
                 idents.use = ct)
}
```


```{r, heatmap, fig.height=6}
# Heatmap
netVisual_heatmap(cch, cluster.rows = TRUE, cluster.cols = TRUE, remove.isolate = TRUE)
```

```{r bubble, fig.height=10}
# (1) show all the significant interactions (L-R pairs) from some cell groups (defined by 'sources.use') to other cell groups (defined by 'targets.use')
netVisual_bubble(cch, sources.use = c('Myofibroblast'),
                 targets.use = c('AT1','AT2 1','AT2 2'),
                 remove.isolate = TRUE)
```


```{r, signaling_scatter}
# Compute the network centrality scores
cch <- netAnalysis_computeCentrality(cch, slot.name = "netP") # the slot 'netP' means the inferred intercellular communication network of signaling pathways

netAnalysis_signalingRole_scatter(cch)
```

```{r, pathways}
# Visualize the computed centrality scores using heatmap, allowing ready identification of major signaling roles of cell groups
netAnalysis_signalingRole_network(cch, width = 12, height = 2.5, font.size = 10,
                                  signaling = 'GAP')
```

```{r, path_avail, echo=FALSE}
print('Available pathways:')
print(cch@netP$pathways)
```
